### ISSUE TITLE
@phyperopt not working

### ISSUE THREAD

**Issue by dfenn** [baggepinnen/Hyperopt.jl#48]
I'm unable to use the @phyperopt macro. Running this code  

```
addprocs(2)
@everywhere using Hyperopt
@everywhere f(a,b=true;c=10) = sum(@. 100 + (a-3)^2 + (b ? 10 : 20) + (c-100)^2)
horp = @phyperopt for i=300, sampler=RandomSampler(), a = LinRange(1,5,50), b = [true, false], c = exp10.(LinRange(-1,3,50))
    # println(i, "\t", a, "\t", b, "\t", c)
    f(a,b,c=c)
end
```

gives the following error:

```
ERROR: LoadError: On worker 6:
UndefVarError: #754#ho not defined
#213 at /home/fenn/.julia/packages/Hyperopt/eYEpe/src/Hyperopt.jl:146
#106 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:294
run_work_thunk at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:79
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:294 [inlined]
#105 at ./task.jl:356
Stacktrace:
 [1] (::Base.var"#770#772")(::Task) at ./asyncmap.jl:178
 [2] foreach(::Base.var"#770#772", ::Array{Any,1}) at ./abstractarray.jl:2009
 [3] maptwice(::Function, ::Channel{Any}, ::Array{Any,1}, ::UnitRange{Int64}) at ./asyncmap.jl:178
 [4] wrap_n_exec_twice(::Channel{Any}, ::Array{Any,1}, ::Distributed.var"#206#209"{WorkerPool}, ::Function, ::UnitRange{Int64}) at ./asyncmap.jl:154
 [5] async_usemap(::Distributed.var"#190#192"{Distributed.var"#190#191#193"{WorkerPool,var"#213#217"}}, ::UnitRange{Int64}; ntasks::Function, batch_size::Nothing) at ./asyncmap.jl:103
 [6] #asyncmap#754 at ./asyncmap.jl:81 [inlined]
 [7] pmap(::Function, ::WorkerPool, ::UnitRange{Int64}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Array{Any,1}, retry_check::Nothing) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/pmap.jl:126
 [8] pmap(::Function, ::WorkerPool, ::UnitRange{Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/pmap.jl:101
 [9] pmap(::Function, ::UnitRange{Int64}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/pmap.jl:156
 [10] pmap(::Function, ::UnitRange{Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/pmap.jl:156
 [11] top-level scope at /home/fenn/.julia/packages/Hyperopt/eYEpe/src/Hyperopt.jl:145
 [12] include(::String) at ./client.jl:457
 [13] top-level scope at REPL[30]:1
```

I'm not particularly familiar with Julia distributed programming, but it looks like `ho` is never defined on the workers. Somewhat confusingly, if I wrap this code in a `@testset "Parallel" begin ... end` block, it executes without errors.

Side note: this code is taken directly from the test suite, with one modification: the actual test suite has the line

```
Distributed.nworkers() == 0 && addprocs(2)
```

On my machine at least, `nworkers()` returns 1 if no workers have been added, so I believe that the test in the test suite may not be adding any additional processors, because `addprocs()` is never being called. When I change this line to 

```
Distributed.nworkers() == 1 && addprocs(2)
```
and rerun the test:

```
(@v1.5) pkg> test Hyperopt
```
This causes a test to fail:

```
Parallel: Test Failed at /home/fenn/.julia/packages/Hyperopt/eYEpe/test/runtests.jl:290
  Expression: length(horp.history) == 400
   Evaluated: 300 == 400
```

This is a different error than the one mentioned above. 

EDIT: wrapping the above code in a function also seems to fix it. I guess it doesn't work when it's top-level.

**Comment by baggepinnen** [comment]
Thanks for the issue! I hope it was fixed by the commit referenced above. Feel free to `pkg> add Hyperopt#master` and see if your example runs fine now. If it does, I'll tag a new release

**Comment by dfenn** [comment]
Great! Just tested it, and both issues above are fixed. Thanks for your very timely response!

**Comment by baggepinnen** [comment]
Oki perfect :) I noticed that CI still failed, but with another error that I didn't see locally. Will see to that being fixed before a new release is tagged.
