### ISSUE TITLE
@phyperopt causes history and results to have different lengths

### ISSUE THREAD

**Issue by PGimenez** [baggepinnen/Hyperopt.jl#7]
I found this out while using @phyperopt with i=6 on a grid with 12 points. When plotting the hyperoptimizer I get the following error 

````
ERROR: LoadError: BoundsError: attempt to access 6-element Array{Any,1} at index [[2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 1, 7]]

throw_boundserror(::Array{Any,1}, ::Tuple{Array{Int64,1}}) at ./abstractarray.jl:484
checkbounds at ./abstractarray.jl:449 [inlined]
_getindex at ./multidimensional.jl:588 [inlined]
getindex(::Array{Any,1}, ::Array{Int64,1}) at ./abstractarray.jl:905
macro expansion at ./show.jl:555 [inlined] (repeats 2 times)
macro expansion at /home/usuaris/spcom/gfebrer/sampling/plotting.jl:19 [inlined]
````

I wrote a minimum working example to test this out

````
using Hyperopt
function f(x,y)
    return x^2+y^2-13
end
xrang = [1,2,3,4]
yrang = xrang
ho = @hyperopt for i=4, x=xrang, y=yrang
    f(x,y)
end

pho = @phyperopt for i=4, x=xrang, y=yrang
    f(x,y)
end

@show ho.history, ho.results
@show pho.history, pho.results
````

The output is
`(ho.history, ho.results) = (Any[[1, 1], [3, 3], [3, 3], [4, 1]], Any[-11, 5, 5, 4])
(pho.history, pho.results) = (Any[[3, 3], [3, 4], [1, 1], [2, 3], (3, 3), (3, 4), (1, 1), (2, 3)], Any[5, 12, -11, 0])`

**Comment by baggepinnen** [comment]
Thanks for the report, I'll have a look at it!

**Comment by baggepinnen** [comment]
Hopefully fixed by ff328fa

**Comment by PGimenez** [comment]
Apparently that didn't fix it :(. I updated to master and ran the MWE again but it still showing the same results.

**Comment by baggepinnen** [comment]
That's strange, the mwe runs on my setup. Are you sure that you got the latest master when you updated? There were no conflicts between packages preventing the update? What does `st Hyperopt` show?

**Comment by PGimenez** [comment]
Sorry, apparently I didn't restart Julia so that it would recompile the cache. Now the code is updated, but the problem is the opposite. @phyperopt returns the correct history but only when there's only one process; if I add more the returned list is empty. This is what I get:

```
`(ho.history, ho.results) = (Any[[1, 3], [2, 1], [1, 2], [3, 3]], Any[-3, -8, -8, 5])
(pho.history, pho.results) = (Any[], Any[5, -11, 19, -8, 7, 0])`
```

May this be because the hyperoptimizer in the macro is not a shared object such as a SharedArray?

**Comment by baggepinnen** [comment]
I can not reproduce your error, it seems to be working here
```julia
pho = @phyperopt for i=4, x=xrang, y=yrang
    @show Distributed.myid()
    f(x,y)
end

      From worker 2:    Distributed.myid() = 2
      From worker 3:    Distributed.myid() = 3
      From worker 3:    Distributed.myid() = 3
      From worker 2:    Distributed.myid() = 2
(ho.history, ho.results) = (Any[[2, 2], [1, 2], [4, 3], [4, 2]], Any[-5, -8, 12, 7])
(pho.history, pho.results) = (Any[(1, 1), (1, 2), (2, 2), (3, 1)], Any[-11, -8, -5, -3])
```

**Comment by baggepinnen** [comment]
Hopefully fixed with https://github.com/baggepinnen/Hyperopt.jl/commit/89e152adcd841fc460298f0c4c6e27cc6f309d66

**Comment by PGimenez** [comment]
It works now, thank you for the fix!
